apiVersion: v1
kind: PersistentVolume
metadata:
  name: blogt-nfspv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/www/html/blogt/posts
    server: mjolnir
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blogt-nfspvc
  namespace: blogt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: blogt-nfspv